### ISSUE TITLE
Bad performance of S4D in v3 compared to before

### ISSUE THREAD

**Issue by ethanbar11** [HazyResearch/state-spaces#59] opened 2022-08-09 09:23 UTC
Hi,
I've just cloned the v3 version of the repository and trying to train on CIFAR with the next command line:

`python -m train experiment=cifar/s4-cifar-ablation trainer.gpus=3 loader.batch_size=150 model.layer.mode=diag`

I'm getting quite bad results (Epoch 34 - val/accuracy 0.606)
When running the following line:

`python -m train experiment=cifar/s4-cifar-ablation trainer.gpus=3 loader.batch_size=150 model.layer.mode=nplr`

(Only changing mode to NPLR)
I'm getting val/accuracy= 0.763 already in Epoch 17.

I've also installed the Cauchy kernel before running both experiments.
Any ideas?

EDIT: After reading the README, I understood I needed to change the measure to diag-lin as well. Silly me, Thanks.

Thanks in advance,
Ethan.

**Comment by albertfgu** [comment] 2022-08-09 18:11
No worries, glad you found the documentation. I'll consider adding a warning to the code as well if a different measure is passed in. Let me know if the performance with `diag-lin` seems to track correctly.

**Comment by albertfgu** [comment] 2022-08-10 18:52
I did a quick reproduction run with the command
```
python -m train experiment=cifar/s4-cifar-ablation loader.batch_size=50 model.layer.mode=diag model.layer.measure=diag-lin
```
and it seems to be tracking: val=77.8 @ 13 epochs, val=81.1 @ 25 epochs.

So I'll close the issue. Feel free to open another for any more performance questions.

**Closed by albertfgu** 2022-08-10 18:52 UTC
